template:
  spec:
    nodeSelector:
      kubernetes.io/os: windows
    containers:
    - name: runner
      volumeMounts:
      - name: cargo-cache
        mountPath: C:\Users\ContainerAdministrator\.cargo\registry
    volumes:
    - name: cargo-cache
      hostPath:
        path: {{ .Values.cargoCachePath }}
        type: DirectoryOrCreate
