template:
  spec:
    containers:
    - name: runner
      volumeMounts:
      - name: cargo-cache
        mountPath: /usr/local/cargo/registry
    volumes:
    - name: cargo-cache
      hostPath:
        path: {{ .Values.cargoCachePath }}
        type: DirectoryOrCreate
